stages:
  - build
  - pkg

build:
  image: golang:latest
  stage: build
  script:
    - make install ETCDIR=./build/inst LIBARCHDIR=/. DESTDIR=./build/inst PREFIX=/.
    - tar cfz libnss_http.tar.gz -C build/inst .
  artifacts:
    expire_in: 30 mins
    paths:
    - libnss_http.tar.gz
  only:
    changes:
      - .gitlab-ci.yml
      - Makefile
      - deb/**/*
      - rpm/**/*
      - src/**/*
  tags:
    - docker

pkg:rpm:
  image: centos:7
  stage: pkg
  script:
    - yum install -y rpmdevtools
    - echo "%_topdir $(pwd)/rpmbuild" > ~/.rpmmacros
    - rpmdev-setuptree
    - cp libnss_http.tar.gz rpmbuild/SOURCES/
    - rpmbuild -bb rpm/libnss-http.spec -D "PKG_VER $(cat VERSION | cut -d'-' -f1)" -D "PKG_REL $(cat VERSION | cut -d'-' -f2)"
  artifacts:
    expire_in: 30 mins
    paths:
    - "rpmbuild/RPMS/*/libnss-http*.rpm"
  only:
    changes:
      - .gitlab-ci.yml
      - Makefile
      - rpm/**/*
      - src/**/*
  tags:
    - docker

pkg:deb:
  image: ubuntu:latest
  stage: pkg
  script:
    - cd deb
    - PKG_VER=$(cat ../VERSION)
    - mkdir -p libnss-http-$PKG_VER/{DEBIAN,etc,lib/x86_64-linux-gnu}
    - cp {control,postinst,postrm} libnss-http-$PKG_VER/DEBIAN/
    - sed -i "s/<PKG_VER>/$PKG_VER/g" libnss-http-$PKG_VER/DEBIAN/control
    - sed -i "s/<PKG_VER>/$(echo $PKG_VER | cut -d'-' -f1)/g" libnss-http-$PKG_VER/DEBIAN/postinst
    - mv ../libnss_http.tar.gz .
    - tar xf libnss_http.tar.gz
    - cp -Pfa libnss_http.so* libnss-http-$PKG_VER/lib/x86_64-linux-gnu/
    - cp -af nss_http.conf libnss-http-$PKG_VER/etc/
    - dpkg-deb -b libnss-http-$PKG_VER
  artifacts:
    expire_in: 30 mins
    paths:
    - deb/libnss-http-*.deb
  only:
    changes:
      - .gitlab-ci.yml
      - Makefile
      - deb/**/*
      - src/**/*
  tags:
    - docker
